# Generated by Django 4.2 on 2024-01-31 07:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DateExcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excelFile",
                    models.FileField(
                        max_length=1000,
                        upload_to="excel/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["xlsx"])
                        ],
                        verbose_name="上传.xlsx文件",
                    ),
                ),
                (
                    "description",
                    models.TextField(default="请上传excel文件", verbose_name="文件备注（选填）"),
                ),
                (
                    "filename",
                    models.CharField(
                        default="程序自动填写", max_length=250, verbose_name="文件名（程序自动填写）"
                    ),
                ),
                (
                    "hash_value",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="文件哈希值"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
            ],
            options={
                "verbose_name": "文件 / 上传.xlsx文件导入数据",
                "verbose_name_plural": "文件 / 上传.xlsx文件导入数据",
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="品牌厂商")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
            ],
            options={"verbose_name": "管理 / 品牌厂商", "verbose_name_plural": "管理 / 品牌厂商",},
        ),
        migrations.CreateModel(
            name="FenLeiInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_dl", models.CharField(max_length=100, verbose_name="商品大类")),
                (
                    "name_form",
                    models.CharField(default="1", max_length=100, verbose_name="数据库表名"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
            ],
            options={"verbose_name": "管理 / 商品大类", "verbose_name_plural": "管理 / 商品大类",},
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="组名"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
            ],
            options={"verbose_name": "管理 / 班组", "verbose_name_plural": "管理 / 班组",},
        ),
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Quyu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="区域名称")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
            ],
            options={"verbose_name": "管理 / 区域", "verbose_name_plural": "管理 / 区域",},
        ),
        migrations.CreateModel(
            name="YinPanInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                (
                    "classify",
                    models.SmallIntegerField(
                        choices=[(1, "1T"), (2, "2T"), (3, "4T"), (4, "6T"), (5, "8T")],
                        default=1,
                        verbose_name="产品类型",
                    ),
                ),
                ("yp_dx", models.SmallIntegerField(default=1, verbose_name="硬盘大小T")),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 硬盘", "verbose_name_plural": "管理 / 硬盘",},
        ),
        migrations.CreateModel(
            name="XsqInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                ("classify", models.CharField(max_length=100, verbose_name="产品类型")),
                ("classify_fl", models.CharField(max_length=100, verbose_name="选择分类")),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 显示器", "verbose_name_plural": "管理 / 显示器",},
        ),
        migrations.CreateModel(
            name="XiancaiInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                (
                    "classify",
                    models.SmallIntegerField(
                        choices=[(1, "网线"), (2, "光皮"), (3, "光缆"), (4, "电源线")],
                        default=2,
                        verbose_name="产品类型",
                    ),
                ),
                ("classify_fl", models.CharField(max_length=100, verbose_name="选择分类")),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 线材", "verbose_name_plural": "管理 / 线材",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_group_vip",
                    models.BooleanField(default=False, verbose_name="是否为组长"),
                ),
                (
                    "is_quyu_vip",
                    models.BooleanField(max_length=False, verbose_name="是否为区域管理"),
                ),
                (
                    "is_management_vip",
                    models.BooleanField(default=False, verbose_name="是否为方案审核专员"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="人员姓名")),
                ("phone_number", models.CharField(max_length=20, verbose_name="手机号")),
                ("pwd", models.CharField(max_length=200, verbose_name="密码")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.group",
                        verbose_name="班组",
                    ),
                ),
                (
                    "quyu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.quyu",
                        verbose_name="区域",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 人员", "verbose_name_plural": "管理 / 人员",},
        ),
        migrations.CreateModel(
            name="SxtInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                (
                    "classify",
                    models.SmallIntegerField(
                        choices=[(1, "半球"), (2, "枪机"), (3, "球机")],
                        default=2,
                        verbose_name="产品类型",
                    ),
                ),
                (
                    "SD",
                    models.SmallIntegerField(
                        choices=[
                            (1, "不支持"),
                            (2, "32"),
                            (3, "64"),
                            (4, "128"),
                            (5, "256"),
                            (6, "512"),
                        ],
                        default=1,
                        verbose_name="SD卡",
                    ),
                ),
                ("is_4G", models.BooleanField(default=False, verbose_name="是否支持4G")),
                (
                    "shuangxiang_yuyin",
                    models.BooleanField(default=False, verbose_name="双向语音"),
                ),
                (
                    "yeshi",
                    models.SmallIntegerField(
                        choices=[(1, "红外"), (2, "全彩")], default=1, verbose_name="夜视"
                    ),
                ),
                (
                    "jiaoju",
                    models.CharField(
                        default="4mm", max_length=300, verbose_name="焦距mm"
                    ),
                ),
                ("px", models.SmallIntegerField(default=400, verbose_name="像素")),
                ("w", models.FloatField(default=0, verbose_name="功耗")),
                (
                    "gongdian_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "POE/DC"), (2, "POE"), (3, "DC")],
                        default=1,
                        verbose_name="供电方式",
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 摄像头", "verbose_name_plural": "管理 / 摄像头",},
        ),
        migrations.CreateModel(
            name="SDCardInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                (
                    "classify",
                    models.SmallIntegerField(
                        choices=[
                            (1, "32G"),
                            (2, "64G"),
                            (3, "128G"),
                            (4, "256G"),
                            (5, "512G"),
                        ],
                        default=1,
                        verbose_name="产品类型",
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / SD卡", "verbose_name_plural": "管理 / SD卡",},
        ),
        migrations.CreateModel(
            name="NVRInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                (
                    "classify",
                    models.SmallIntegerField(
                        choices=[
                            (1, "4路NVR"),
                            (2, "8路NVR"),
                            (3, "16路NVR"),
                            (4, "32路NVR"),
                            (5, "64路NVR"),
                        ],
                        default=1,
                        verbose_name="产品分类",
                    ),
                ),
                ("jierunshu", models.SmallIntegerField(default=4, verbose_name="最大接入")),
                ("yingpanwei", models.SmallIntegerField(default=1, verbose_name="硬盘位")),
                (
                    "max_v",
                    models.CharField(
                        default="10T", max_length=100, verbose_name="单盘最大容量"
                    ),
                ),
                ("is_poe", models.BooleanField(default=False, verbose_name="是否POE录像机")),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / NVR", "verbose_name_plural": "管理 / NVR",},
        ),
        migrations.CreateModel(
            name="Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(verbose_name="方案内容")),
                ("name", models.CharField(max_length=200, verbose_name="方案名称")),
                (
                    "nid",
                    models.CharField(
                        default="202401311552349392", max_length=20, verbose_name="编号"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "未审核"), (2, "审核通过"), (3, "审核失败")],
                        default=1,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                        verbose_name="提交方案的用户",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 方案", "verbose_name_plural": "管理 / 方案",},
        ),
        migrations.CreateModel(
            name="LyqInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                (
                    "classify",
                    models.SmallIntegerField(
                        choices=[(1, "一体化"), (2, "企业路由"), (3, "桌面路由")],
                        default=1,
                        verbose_name="产品类型",
                    ),
                ),
                (
                    "daijialiang",
                    models.SmallIntegerField(default=100, verbose_name="典型带机量"),
                ),
                (
                    "ap_number",
                    models.SmallIntegerField(default=50, verbose_name="可管理AP数"),
                ),
                (
                    "wuxian_canshu",
                    models.BooleanField(default=False, verbose_name="无线参数"),
                ),
                (
                    "wamgkou_leixing",
                    models.SmallIntegerField(
                        choices=[(1, "千兆"), (2, "百兆")], default=1, verbose_name="网口类型"
                    ),
                ),
                (
                    "WAN_LAN",
                    models.SmallIntegerField(default=0, verbose_name="WAN/LAN可变"),
                ),
                ("POE", models.SmallIntegerField(default=0, verbose_name="POE口")),
                (
                    "Console",
                    models.BooleanField(default=False, verbose_name="Console口"),
                ),
                (
                    "PoE_w",
                    models.SmallIntegerField(default=0, verbose_name="PoE总功率/单口功率"),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 路由器", "verbose_name_plural": "管理 / 路由器",},
        ),
        migrations.CreateModel(
            name="JiGuiInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                (
                    "classify",
                    models.SmallIntegerField(
                        choices=[
                            (1, "4U机柜"),
                            (2, "6U机柜"),
                            (3, "9U机柜"),
                            (4, "12U机柜"),
                            (5, "18U机柜"),
                            (6, "32U机柜"),
                        ],
                        default=1,
                        verbose_name="产品类型",
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 机柜", "verbose_name_plural": "管理 / 机柜",},
        ),
        migrations.CreateModel(
            name="JhjInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                (
                    "classify",
                    models.SmallIntegerField(
                        choices=[
                            (1, "普通百兆"),
                            (1, "普通百兆"),
                            (2, "普通千兆"),
                            (3, "POE百兆"),
                            (4, "POE千兆"),
                            (5, "三层交换"),
                        ],
                        default=1,
                        verbose_name="产品类型",
                    ),
                ),
                ("is_poe", models.BooleanField(default=False, verbose_name="是否POE交换机")),
                (
                    "port_number",
                    models.SmallIntegerField(default=0, verbose_name="端口总数"),
                ),
                (
                    "upstream_number",
                    models.SmallIntegerField(
                        default=0, help_text="独立的上联口", verbose_name="上联端口数"
                    ),
                ),
                (
                    "lan_number",
                    models.SmallIntegerField(default=0, verbose_name="lan端口数"),
                ),
                (
                    "poe_number",
                    models.SmallIntegerField(default=0, verbose_name="POE端口数"),
                ),
                (
                    "guang_mokuai",
                    models.SmallIntegerField(default=0, verbose_name="光模块口"),
                ),
                (
                    "Console",
                    models.BooleanField(default=False, verbose_name="Console口"),
                ),
                ("PoE_w", models.SmallIntegerField(default=0, verbose_name="PoE总功率W")),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 交换机", "verbose_name_plural": "管理 / 交换机",},
        ),
        migrations.AddField(
            model_name="group",
            name="quyu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.quyu",
                verbose_name="区域",
            ),
        ),
        migrations.CreateModel(
            name="FucaiInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                ("classify", models.CharField(max_length=100, verbose_name="产品类型")),
                ("classify_fl", models.CharField(max_length=100, verbose_name="选择分类")),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / 辅材", "verbose_name_plural": "管理 / 辅材",},
        ),
        migrations.CreateModel(
            name="ApInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_kind", models.CharField(max_length=100, verbose_name="产品型号")),
                (
                    "gonghuo_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "标品"), (2, "市采"), (3, "省采")],
                        default=1,
                        verbose_name="供货方式",
                    ),
                ),
                ("canshu_gaiyao", models.TextField(default="..", verbose_name="参数概要")),
                (
                    "jinhuojia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="进货价"
                    ),
                ),
                (
                    "yunwei",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="集成运维费"
                    ),
                ),
                (
                    "xiaoshoujia",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="销售价"
                    ),
                ),
                (
                    "city_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工电信单价",
                    ),
                ),
                (
                    "v_e_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工电信单价",
                    ),
                ),
                (
                    "city_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="城区施工员工单价",
                    ),
                ),
                (
                    "v_f_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="农村施工员工单价",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="排序规则，越小越排在前面（取值大于0）"
                    ),
                ),
                (
                    "classify",
                    models.SmallIntegerField(
                        choices=[(1, "面板式AP"), (2, "吸顶式AP")],
                        default=1,
                        verbose_name="产品类型",
                    ),
                ),
                (
                    "color",
                    models.CharField(default="...", max_length=100, verbose_name="颜色"),
                ),
                (
                    "lianjie_sulv",
                    models.SmallIntegerField(default=0, verbose_name="连接速率Mbps"),
                ),
                (
                    "wifi_level",
                    models.SmallIntegerField(
                        choices=[(5, "5"), (6, "6"), (7, "7")],
                        default=6,
                        verbose_name="wifi几",
                    ),
                ),
                (
                    "gongdian_fangshi",
                    models.SmallIntegerField(
                        choices=[(1, "POE/DC"), (2, "POE"), (3, "DC")],
                        default=1,
                        verbose_name="供电方式",
                    ),
                ),
                ("w", models.FloatField(default=0, verbose_name="整机功耗,W")),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.factory",
                        verbose_name="品牌厂商",
                    ),
                ),
            ],
            options={"verbose_name": "管理 / AP", "verbose_name_plural": "管理 / AP",},
        ),
    ]
